name: Deploy Production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Debug GITHUB_REF
        run: echo "GITHUB_REF is ${{ github.ref }}"

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        env:
          TAG_NAME: ${{ github.ref_name }}
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Переход в директорию prod окружения
            cd /home/hallofheroes/prod
            
            # Обновление кода из репозитория и переключение на тег
            git fetch --all --tags --force || { echo "Failed to fetch tags"; exit 1; }
            git checkout $TAG_NAME || { echo "Failed to checkout $TAG_NAME"; exit 1; }
            echo "Checkout version $TAG_NAME at $(date)"
            
            # Установка и сборка бэкенда
            cd apps/backend
            npm i
            npm run build
            
            # Установка и сборка фронтенда
            cd ../frontend
            npm i
            npm run build
                        
            # Возврат в корневую директорию проекта
            cd /home/hallofheroes/prod
            
            # Рестарт PM2 процесса
            pm2 restart hall-of-heroes-backend || npm run start:pm2
